### ISSUE TITLE
Free items in stores

### ISSUE THREAD

**Issue by rekterakathom** [rekterakathom/Overthrow#41]
Sometimes items (often binoculars) appear in shop inventories as free items, and these items often appear duplicated as well.
![20221222203714_1](https://user-images.githubusercontent.com/30532050/209203983-60be62b8-2c1e-4957-aaea-6c726585f46d.jpg)

**Comment by Tuupertunut** [comment]
Are those RHS binoculars? I think that is a non-item base class being sold. This may get automatically fixed in my next PR.

**Comment by Tuupertunut** [comment]
This may be fixed in #43 but I'm not sure.

**Comment by rekterakathom** [comment]
Issue persists after merging #43 
![20221225192109_1](https://user-images.githubusercontent.com/30532050/209476895-17359875-1b69-47d4-8104-b7c3dfd1b135.jpg)

**Comment by rekterakathom** [comment]
Fixed in 1.7.0
